with open('assets/index-2d1L6cXj.js.bak', 'r', encoding='utf-8') as f:
    content = f.read()

old_venue = '''function D_(){return(0,O.jsxs)(`section`,{className:`px-6 pb-20 text-center sm:pb-28`,children:[(0,O.jsxs)(Xg,{children:[(0,O.jsx)(Yg,{className:`mb-10`}),(0,O.jsx)(`p`,{className:`caps text-[0.6rem] text-olive`,children:`The venue`}),(0,O.jsx)(`h2`,{className:`script mt-4 text-4xl text-ink sm:text-5xl`,children:$.venue.name}),(0,O.jsx)(`p`,{className:`mx-auto mt-3 max-w-xs text-base leading-relaxed text-sepia`,children:$.venue.address})]}),(0,O.jsx)(Xg,{delay:.15,children:(0,O.jsx)(Q.a,{href:Vg,target:`_blank`,rel:`noreferrer`,onClick:E_,whileTap:{scale:.985},className:`grain group mx-auto mt-8 block max-w-md overflow-hidden rounded-sm border border-border shadow-[0_20px_40px_-34px_rgba(60,45,25,0.75)]`,children:(0,O.jsxs)(`div`,{className:`relative`,children:[(0,O.jsx)(`img`,{src:T_,alt:`Map showing the location of ${$.venue.name}`,width:1024,height:768,loading:`lazy`,className:`h-52 w-full object-cover transition-transform duration-[1.2s] ease-out group-hover:scale-[1.04] sm:h-60`}),(0,O.jsx)(Q.span,{"aria-hidden":`true`,className:`absolute left-1/2 top-1/2 size-3 -translate-x-1/2 -translate-y-1/2 rounded-full bg-gold ring-8 ring-gold/20`,animate:{scale:[1,1.35,1],opacity:[1,.75,1]},transition:{duration:2.4,repeat:1/0,ease:`easeInOut`}}),(0,O.jsx)(`span`,{className:`caps absolute bottom-3 left-1/2 flex min-h-11 -translate-x-1/2 items-center rounded-full bg-paper/85 px-5 text-[0.5rem] text-ink backdrop-blur-sm`,children:`Open in maps`})]})})}),(0,O.jsx)(Xg,{delay:.25,children:(0,O.jsx)(Q.a,{href:Hg,target:`_blank`,rel:`noreferrer`,onClick:E_,whileTap:{scale:.96},className:`caps mt-6 inline-flex min-h-14 items-center gap-2 rounded-full border border-ink/25 px-8 text-[0.55rem] text-ink transition-colors duration-500 hover:border-ink hover:bg-ink hover:text-paper`,children:`Get directions`})})]})}'''

old_I = '''function I_(){M_();let[e,t]=(0,b.useState)(!1);return(0,O.jsxs)(O.Fragment,{children:[(0,O.jsx)(__,{onOpen:()=>t(!0)}),(0,O.jsx)(w_,{}),(0,O.jsxs)(`main`,{className:`grain relative min-h-screen bg-paper text-ink`,style:{backgroundImage:`url(${ua})`,backgroundSize:`480px`},children:[(0,O.jsx)(b_,{ready:e}),(0,O.jsx)(C_,{}),(0,O.jsx)(r_,{}),(0,O.jsx)(D_,{}),(0,O.jsx)($g,{}),(0,O.jsx)(S_,{})]}),(0,O.jsx)(Jg,{})]})}'''

print('old_venue FOUND:', old_venue in content)
print('old_I FOUND:', old_I in content)
